const gulp = require('gulp');
const less = require('gulp-less');
const gutil = require('gulp-util');
const minifyCSS = require('gulp-minify-css');
const uglify = require('gulp-uglify');
const chalk = require('chalk');
const logger = require('gulp-logger');
const rename = require('gulp-rename');
const coffee = require('gulp-coffee');
const concat = require('gulp-concat');

gulp.task('app_css', function () {
  gulp.src('assets/css/**/*')
    .pipe(minifyCSS({
      keepSpecialComments: 1
    }))
    .pipe(rename({
      suffix: '.min'
    }))
    .pipe(gulp.dest('./assets/dist/css'));
});

gulp.task('app_fonts', function () {
  gulp.src('assets/fonts/*.*')
    .pipe(gulp.dest('./assets/dist/fonts'));
});

gulp.task('app_scripts', function () {
  gulp.src('assets/js/app/core.js')
    .pipe(concat('app.js'))
    .pipe(rename({
      suffix: '.min'
    }))
    .pipe(gulp.dest('./assets/dist/js/app'));
});

gulp.task('app_system', function () {
  gulp.src('assets/js/app/system.js')
    .pipe(uglify())
    .pipe(concat('system.js'))
    .pipe(rename({
      suffix: '.min'
    }))
    .pipe(gulp.dest('./assets/dist/js/app'));
});

gulp.task('vendor_scripts', function () {
  gulp.src([
      'assets/js/vendor/jquery.js',
      'assets/js/vendor/bootstrap.js',
      'assets/js/vendor/ripples.js',
      'assets/js/vendor/material.js'
    ])
    .pipe(uglify({
      preserveComments: 'all'
    }))
    .pipe(concat('vendor.js'))
    .pipe(rename({
      suffix: '.min'
    }))
    .pipe(gulp.dest('./assets/dist/js/vendor/'));
});

gulp.task('build', ['app_css', 'app_fonts', 'app_scripts', 'app_system', 'vendor_scripts']);

gulp.task('default', ['build']);

// ---
// generated by coffee-script 1.9.2